language: ruby
cache: bundler
sudo: false
before_install:
  - gem install bundler
  - gem update --system
  - gem --version
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
rvm:
  - 2.4.3
services:
  - postgresql