language: ruby
sudo: false
before_install:
  - gem install bundler
  - gem update --system
  - gem --version
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
rvm:
  - 2.5.1
services:
  - postgresql
