language: ruby
cache: bundler
sudo: false
before_install:
  - gem install bundler
  - gem update --system
  - gem --version
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
before_script:
  - cp config/database.yml.travis config/database.yml
rvm:
  - 2.4.3
services:
  - postgresql