language: ruby
cache: bundler
sudo: false
before_install:
  - gem install bundler
  - gem update --system
  - gem --version
before_script:
  - psql -c 'create database spotibot_test;' -U postgres
rvm:
  - 2.5.1
services:
  - postgresql
